# Generated by Django 2.2.7 on 2020-10-27 01:12

import applicant.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('education', models.TextField()),
                ('contact', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('rate', models.IntegerField()),
                ('rate_number', models.IntegerField()),
                ('comment', djongo.models.fields.ArrayField(model_container=applicant.models.Comment, model_form_class=applicant.models.CommentForm)),
            ],
        ),
    ]
